name: Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
        id: install
        with:
          hugo-version: "0.148.1"
          extended: true
      - name: Set env to production
        uses: mikefarah/yq@8f3291d3165497b360b8ffee3c887624bb6fa1cf # master
        with:
          cmd: yq eval -i '.params.env = "production"' 'hugo.yml'
      - name: Don't publish drafts
        uses: mikefarah/yq@8f3291d3165497b360b8ffee3c887624bb6fa1cf # master
        with:
          cmd: yq eval -i '.buildDrafts = "false"' 'hugo.yml'
      - name: Generate highlight CSS
        run: hugo gen chromastyles --style fruity --highlightStyle "bg:#7782bb6b" > assets/css/extended/fruity.css
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          cname: nonsense.fyi
